name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    # Permissions for pushing tags
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install

      # Linttaus
      - name: Check style
        run: npm run eslint

      # Jest
      - name: Run unit tests
        run: npm test

      # Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Playwright E2E tests
      - name: Run E2E tests
        run: npm run test:pw

      # Deployment to render
      - name: Debug Render secrets
        run: |
          echo "SERVICE_ID length:"
          echo "${{ secrets.RENDER_SERVICE_ID }}" | awk '{ print length }'

          echo "API_KEY length:"
          echo "${{ secrets.RENDER_API_KEY }}" | awk '{ print length }'

      - name: Trigger deployment
        run: curl "https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}"

      # Version tag
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
