name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install

      # Linttaus
      - name: Check style
        run: npm run eslint

      # Jest
      - name: Run unit tests
        run: npm test

      # Playwright brosersers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Playwright E2E tests
      - name: Run E2E tests
        run: npm run test:pw

      # Deployment to render
      - name: Debug Render secrets
        run: |
          echo "SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}" | sed 's/.....$/***** /'
          echo "API_KEY starts with xntc- ?"
          echo "${{ secrets.RENDER_API_KEY }}" | grep -q "^xntc-" && echo "OK" || echo "WRONG FORMAT"

      - name: Trigger deployment
        run: curl "https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}"

      # - name: Build application
      #   run: npm run build
      # - name: Deploy application
      #   run: |
      #     echo "Deploying application..."
      #     npm run start-prod
